# Generated by Django 5.1.1 on 2025-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioticdata',
            name='collectlocation',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='bioticdata',
            name='collectno',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='bioticdata',
            name='fdatex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bioticdata',
            name='fdetailx',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='bioticdata',
            name='freshweigth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bioticdata',
            name='measurecode',
            field=models.CharField(default=10, max_length=50),
        ),
        migrations.AlterField(
            model_name='bioticdata',
            name='nspecies',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='bioticdata',
            name='origin',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='bioticdata',
            name='subsample',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='fishdetails',
            name='collectno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
