# Generated by Django 5.1.1 on 2025-01-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0002_alter_bioticdata_collectlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioticdata',
            name='collectno',
            field=models.IntegerField(default=0),
        ),
    ]
