# Generated by Django 5.1.1 on 2025-01-15 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0003_alter_bioticdata_collectno'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetails',
            name='biotic',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='fish_details', to='fyke.bioticdata'),
            preserve_default=False,
        ),
    ]
