# Generated by Django 5.1.1 on 2025-01-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0004_fishdetails_biotic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='collect',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='version',
        ),
    ]
