# Generated by Django 5.1.1 on 2025-01-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0005_remove_datacollection_collect_and_more'),
        ('maintenance', '0002_alter_fykelocation_table_alter_fykeprogramme_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FykeStomachData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyke.fishdetails')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancespecieslist')),
            ],
            options={
                'verbose_name': 'Fyke Stomach Data',
                'verbose_name_plural': 'Fyke Stomach Data',
                'db_table': 'fyke_stomachdata',
            },
        ),
    ]
