# Generated by Django 5.1.1 on 2025-01-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0006_fykestomachdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fykestomachdata',
            old_name='fish',
            new_name='fishdetails',
        ),
    ]
