# Generated by Django 5.1.1 on 2025-01-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0007_rename_fish_fykestomachdata_fishdetails'),
        ('maintenance', '0002_alter_fykelocation_table_alter_fykeprogramme_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FykeStomachData',
            new_name='StomachData',
        ),
        migrations.RenameField(
            model_name='bioticdata',
            old_name='date',
            new_name='datacollection',
        ),
        migrations.RenameField(
            model_name='bioticdata',
            old_name='fishid',
            new_name='species',
        ),
    ]
