# Generated by Django 5.1.1 on 2025-01-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyke', '0008_rename_fykestomachdata_stomachdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bioticdata',
            old_name='freshweigth',
            new_name='freshweight',
        ),
    ]
