# Generated by Django 5.1.1 on 2024-12-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=50)),
                ('collectlocation', models.CharField(default='Texel (RW) Lauwersoog (RW)', max_length=100)),
                ('yearFrom', models.CharField(default='2024', max_length=10)),
                ('yearUntil', models.CharField(default=9999, max_length=4)),
                ('accessTexel', models.IntegerField(default=3)),
                ('accessLauwersoog', models.IntegerField(default=3)),
                ('fishdata', models.IntegerField(default=3)),
                ('deleteRecords', models.IntegerField(default=3)),
                ('fishdataExport', models.IntegerField(default=3)),
                ('fishdataRecords', models.IntegerField(default=3)),
                ('fishdataSource', models.IntegerField(default=3)),
                ('fyke', models.IntegerField(default=3)),
                ('fykeBioticdata', models.IntegerField(default=3)),
                ('fykeDatacollection', models.IntegerField(default=3)),
                ('fykeExportdata', models.IntegerField(default=3)),
                ('fykeFishDetails', models.IntegerField(default=3)),
                ('fykeLocations', models.IntegerField(default=3)),
                ('help', models.IntegerField(default=3)),
                ('maintenance', models.IntegerField(default=3)),
                ('maintenanceFishprogrammes', models.IntegerField(default=3)),
                ('maintenanceLocations', models.IntegerField(default=3)),
                ('maintenanceSpecies', models.IntegerField(default=3)),
                ('manager', models.IntegerField(default=3)),
                ('managerUserAccess', models.IntegerField(default=3)),
                ('options', models.IntegerField(default=3)),
                ('optionsUserSettings', models.IntegerField(default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gebruiker',
                'verbose_name_plural': 'Gebruikers',
                'db_table': 'adminmenu_person',
            },
        ),
    ]
