# Generated by Django 5.1.1 on 2025-01-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='yearFrom',
            field=models.CharField(default='2025', max_length=10),
        ),
    ]
