# Generated by Django 5.1.1 on 2025-01-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fykelocation',
            table='maintenance_fyke_locations',
        ),
        migrations.AlterModelTable(
            name='fykeprogramme',
            table='maintenance_fyke_programmes',
        ),
    ]
