# Generated by Django 5.1.5 on 2025-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_fykelocation_table_alter_fykeprogramme_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancespecieslist',
            name='pauly_trophic_level',
            field=models.CharField(max_length=51),
        ),
    ]
