# Generated by Django 5.1.5 on 2025-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancespecieslist_pauly_trophic_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancespecieslist',
            name='indivweek',
        ),
        migrations.AlterField(
            model_name='maintenancespecieslist',
            name='en_name',
            field=models.CharField(max_length=254),
        ),
    ]
